# Generated by Django 4.1.3 on 2022-12-13 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsCustomers',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False, verbose_name='id customer')),
                ('amount', models.CharField(max_length=100, null=True, verbose_name='Amount of products')),
                ('product_name', models.CharField(max_length=100, null=True, verbose_name='Product Name')),
                ('quantity', models.IntegerField(verbose_name='Quiantity')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer', verbose_name='id customer')),
            ],
        ),
    ]
