# Generated by Django 4.1.3 on 2022-12-23 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('paternal_surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('admin', 'administrator'), ('super', 'super_administrator')], default='admin', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Payments_customers',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.customers')),
            ],
        ),
    ]
